#!/usr/bin/env python3
"""0815-salvage のアセット一式を生成する。

方針:
  - **依存を足さない**（Python 標準ライブラリのみ。動画だけ ffmpeg を使う）
  - **決定論的**（seed 固定。再実行すると同じバイト列が出る）
  - **著作権クリーン**（全部その場で合成する）

生成物は Sources/Sketch0815Salvage/Resources/ 配下へ置き、リポジトリへコミットする。
実行時生成にしないのは、この作品が「アセット経路（ファイル → Bundle → loadModel /
loadSound / loadVideo / loadImage）」そのものを検証対象にしているため。

    python3 scripts/gen-assets.py
"""

from __future__ import annotations

import math
import shutil
import struct
import subprocess
import sys
import wave
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "Sources" / "Sketch0815Salvage" / "Resources"

SAMPLE_RATE = 22050


# --- 決定論的な乱数（random モジュールの実装差を避けて自前で持つ） ----------------


class Rng:
    """線形合同法。Python のバージョン差に依存しないことだけが取り柄。"""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next_u32(self) -> int:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state

    def uniform(self, lo: float = 0.0, hi: float = 1.0) -> float:
        return lo + (hi - lo) * (self.next_u32() / 0xFFFFFFFF)


# --- OBJ -------------------------------------------------------------------


def normalize(v):
    length = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    if length < 1e-9:
        return (0.0, 1.0, 0.0)
    return (v[0] / length, v[1] / length, v[2] / length)


def face_normal(a, b, c):
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    return normalize((uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx))


def spherical_uv(v):
    x, y, z = normalize(v)
    u = 0.5 + math.atan2(z, x) / (2 * math.pi)
    w = 0.5 - math.asin(max(-1.0, min(1.0, y))) / math.pi
    return (u, w)


def write_obj(path: Path, verts, faces, name: str) -> None:
    """三角形リストをフラットシェーディングの OBJ として書く。

    metaphor の loadModel は Model I/O 経由（.mtl は読まない）。マテリアルは
    スケッチ側で fill / metallic / roughness を与える前提なので、ここでは
    v / vt / vn / f だけを書く。

    **Y を反転して書き出す**。metaphor の 3D は Processing 由来で +Y が画面下なので、
    モデル空間で「上」に作ったものはそのままだと上下逆さに描かれる。ここで一度だけ
    畳んでおけば、スケッチ側は素直に置ける（面の巻き順も合わせて反転する）。
    """
    verts = [(v[0], -v[1], v[2]) for v in verts]
    faces = [(f[0], f[2], f[1]) for f in faces]
    lines = [f"# {name} — generated by scripts/gen-assets.py (do not edit by hand)"]
    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    for v in verts:
        u, w = spherical_uv(v)
        lines.append(f"vt {u:.6f} {w:.6f}")
    normals = []
    for f in faces:
        normals.append(face_normal(verts[f[0]], verts[f[1]], verts[f[2]]))
    for n in normals:
        lines.append(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}")
    for i, f in enumerate(faces):
        a, b, c = f[0] + 1, f[1] + 1, f[2] + 1
        ni = i + 1
        lines.append(f"f {a}/{a}/{ni} {b}/{b}/{ni} {c}/{c}/{ni}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def icosahedron():
    t = (1.0 + math.sqrt(5.0)) / 2.0
    verts = [
        (-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0),
        (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
        (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1),
    ]
    verts = [normalize(v) for v in verts]
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1),
    ]
    return verts, faces


def subdivide(verts, faces, steps: int):
    verts = list(verts)
    for _ in range(steps):
        cache: dict[tuple[int, int], int] = {}
        new_faces = []

        def midpoint(i: int, j: int) -> int:
            key = (min(i, j), max(i, j))
            if key in cache:
                return cache[key]
            a, b = verts[i], verts[j]
            m = normalize(((a[0] + b[0]) / 2, (a[1] + b[1]) / 2, (a[2] + b[2]) / 2))
            verts.append(m)
            cache[key] = len(verts) - 1
            return cache[key]

        for a, b, c in faces:
            ab, bc, ca = midpoint(a, b), midpoint(b, c), midpoint(c, a)
            new_faces += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]
        faces = new_faces
    return verts, faces


def value_noise3(rng_table, v, freq: float) -> float:
    """格子点の擬似乱数を三線形補間しただけの安物ノイズ。岩の凹凸用。"""
    x, y, z = v[0] * freq, v[1] * freq, v[2] * freq
    xi, yi, zi = math.floor(x), math.floor(y), math.floor(z)
    xf, yf, zf = x - xi, y - yi, z - zi

    def smooth(t):
        return t * t * (3 - 2 * t)

    sx, sy, sz = smooth(xf), smooth(yf), smooth(zf)
    total = 0.0
    for dz in (0, 1):
        for dy in (0, 1):
            for dx in (0, 1):
                key = ((xi + dx) * 73856093) ^ ((yi + dy) * 19349663) ^ ((zi + dz) * 83492791)
                g = rng_table[key % len(rng_table)]
                wx = sx if dx else 1 - sx
                wy = sy if dy else 1 - sy
                wz = sz if dz else 1 - sz
                total += g * wx * wy * wz
    return total


def make_rock(seed: int, subdiv: int, amount: float, freq: float, squash=(1.0, 1.0, 1.0)):
    verts, faces = subdivide(*icosahedron(), steps=subdiv)
    rng = Rng(seed)
    table = [rng.uniform(-1.0, 1.0) for _ in range(512)]
    out = []
    for v in verts:
        n = value_noise3(table, v, freq)
        r = 1.0 + amount * n
        out.append((v[0] * r * squash[0], v[1] * r * squash[1], v[2] * r * squash[2]))
    return out, faces


def make_tube(radius_top: float, radius_bottom: float, height: float, segments: int, twist: float = 0.0):
    """円柱 / 円錐台。柱・タービン軸に使う。y は ±height/2。"""
    verts = []
    faces = []
    for i in range(segments):
        a = 2 * math.pi * i / segments
        verts.append((radius_top * math.cos(a + twist), height / 2, radius_top * math.sin(a + twist)))
    for i in range(segments):
        a = 2 * math.pi * i / segments
        verts.append((radius_bottom * math.cos(a), -height / 2, radius_bottom * math.sin(a)))
    top_center = len(verts)
    verts.append((0.0, height / 2, 0.0))
    bottom_center = len(verts)
    verts.append((0.0, -height / 2, 0.0))
    for i in range(segments):
        j = (i + 1) % segments
        faces.append((i, segments + i, segments + j))
        faces.append((i, segments + j, j))
        faces.append((top_center, j, i))
        faces.append((bottom_center, segments + i, segments + j))
    return verts, faces


def merge(*parts):
    """(verts, faces) を平行移動・回転つきで連結する。要素は (verts, faces, offset)。"""
    verts: list[tuple[float, float, float]] = []
    faces: list[tuple[int, int, int]] = []
    for part_verts, part_faces, offset in parts:
        base = len(verts)
        for v in part_verts:
            verts.append((v[0] + offset[0], v[1] + offset[1], v[2] + offset[2]))
        for f in part_faces:
            faces.append((f[0] + base, f[1] + base, f[2] + base))
    return verts, faces


def rotate_y(verts, angle: float):
    ca, sa = math.cos(angle), math.sin(angle)
    return [(v[0] * ca - v[2] * sa, v[1], v[0] * sa + v[2] * ca) for v in verts]


def scale_verts(verts, sx: float, sy: float, sz: float):
    return [(v[0] * sx, v[1] * sy, v[2] * sz) for v in verts]


def build_models(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)

    # プレイヤー機: 潰した八面体 + 左右のポッド
    body_v, body_f = subdivide(*icosahedron(), steps=1)
    body_v = scale_verts(body_v, 1.0, 0.45, 1.35)
    pod_v, pod_f = make_tube(0.16, 0.22, 0.9, 10)
    pod_v = [(v[0], v[2], v[1]) for v in pod_v]  # 前後方向へ寝かせる
    verts, faces = merge(
        (body_v, body_f, (0, 0, 0)),
        (pod_v, pod_f, (0.62, -0.05, -0.1)),
        (pod_v, pod_f, (-0.62, -0.05, -0.1)),
    )
    write_obj(out / "drone.obj", verts, faces, "drone (player)")

    # コア: 二十面体をそのまま（収集物。全ステージ共通の形で色だけ変える）
    verts, faces = subdivide(*icosahedron(), steps=1)
    write_obj(out / "core.obj", verts, faces, "core (pickup)")

    # ビーコン: ゴール標識。全ステージで共有するアセット（寿命境界の対照）。
    # 上が細く下が太い塔 + 中ほどの細いリング（皿に見えないよう縦横比を強く取る）
    spire_v, spire_f = make_tube(0.06, 0.26, 3.4, 8)
    ring_v, ring_f = make_tube(0.42, 0.42, 0.08, 16)
    base_v, base_f = make_tube(0.34, 0.46, 0.22, 8)
    verts, faces = merge(
        (spire_v, spire_f, (0, 0, 0)),
        (ring_v, ring_f, (0, 0.55, 0)),
        (base_v, base_f, (0, -1.6, 0)),
    )
    write_obj(out / "beacon.obj", verts, faces, "beacon (shared across stages)")

    # stage1 hull: 丸みのある岩塊
    verts, faces = make_rock(seed=1337, subdiv=2, amount=0.28, freq=1.7)
    write_obj(out / "rock_hull.obj", verts, faces, "rock (stage: hull)")

    # stage2 reactor: 角柱の束
    p1_v, p1_f = make_tube(0.42, 0.5, 2.6, 6)
    p2_v, p2_f = make_tube(0.3, 0.36, 1.7, 6)
    p3_v, p3_f = make_tube(0.24, 0.3, 1.1, 6)
    verts, faces = merge(
        (p1_v, p1_f, (0, 0, 0)),
        (rotate_y(p2_v, 0.6), p2_f, (0.62, -0.4, 0.2)),
        (rotate_y(p3_v, 1.2), p3_f, (-0.5, -0.7, -0.35)),
    )
    write_obj(out / "pillar_reactor.obj", verts, faces, "pillar (stage: reactor)")

    # stage3 vent: 尖った破片
    verts, faces = make_rock(seed=9001, subdiv=1, amount=0.55, freq=3.4, squash=(0.7, 1.6, 0.7))
    write_obj(out / "shard_vent.obj", verts, faces, "shard (stage: vent)")


# --- PNG -------------------------------------------------------------------


def write_png(path: Path, width: int, height: int, pixels) -> None:
    """RGBA8 の PNG を標準ライブラリだけで書く。"""
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter type: None
        row = pixels[y]
        for px in row:
            raw += bytes(px)

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (
            struct.pack(">I", len(data))
            + tag
            + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
        )

    header = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
    png = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + chunk(b"IEND", b"")
    )
    path.write_bytes(png)


def floor_texture(path: Path, size: int, base, accent, seed: int, cell: int) -> None:
    """床タイル。グリッド + 斑（ステージごとに色と粒度を変える）。"""
    rng = Rng(seed)
    table = [rng.uniform(0.0, 1.0) for _ in range(1024)]
    rows = []
    for y in range(size):
        row = []
        for x in range(size):
            # グリッド線
            gx = min(x % cell, cell - 1 - (x % cell))
            gy = min(y % cell, cell - 1 - (y % cell))
            edge = 1.0 if min(gx, gy) < 2 else 0.0
            # 斑（セルごとの明度差）
            key = ((x // cell) * 73856093) ^ ((y // cell) * 19349663)
            patch = table[key % len(table)] * 0.35
            # 細かいざらつき
            grain = table[((x * 31 + y * 17) ^ seed) % len(table)] * 0.12
            t = patch + grain
            r = base[0] * (1 - t) + accent[0] * t
            g = base[1] * (1 - t) + accent[1] * t
            b = base[2] * (1 - t) + accent[2] * t
            if edge:
                r = min(255, r * 0.45 + accent[0] * 0.5)
                g = min(255, g * 0.45 + accent[1] * 0.5)
                b = min(255, b * 0.45 + accent[2] * 0.5)
            row.append((int(r), int(g), int(b), 255))
        rows.append(row)
    write_png(path, size, size, rows)


def build_images(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    # 床は「影が乗る面」でもあるので、暗く作ると落ちた影と見分けが付かなくなる。
    # ベースを中間調まで上げ、アクセントとの差でタイルを見せる。
    floor_texture(out / "floor_hull.png", 256, (86, 116, 128), (152, 204, 212), seed=11, cell=32)
    floor_texture(out / "floor_reactor.png", 256, (118, 84, 62), (214, 152, 96), seed=23, cell=24)
    floor_texture(out / "floor_vent.png", 256, (86, 78, 118), (176, 156, 232), seed=37, cell=40)


# --- WAV -------------------------------------------------------------------


def write_wav(path: Path, samples) -> None:
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        frames = bytearray()
        for s in samples:
            v = int(max(-1.0, min(1.0, s)) * 32000)
            frames += struct.pack("<h", v)
        w.writeframes(bytes(frames))


def ambience(path: Path, seconds: float, partials, noise_level: float, seed: int) -> None:
    """周期が整数回入る正弦波だけで組んだ環境音。継ぎ目なくループする。"""
    total = int(SAMPLE_RATE * seconds)
    rng = Rng(seed)
    table = [rng.uniform(-1.0, 1.0) for _ in range(4096)]
    samples = []
    for i in range(total):
        t = i / SAMPLE_RATE
        v = 0.0
        for cycles, amp in partials:
            freq = cycles / seconds  # seconds 内にちょうど cycles 回
            v += amp * math.sin(2 * math.pi * freq * t)
        # ゆっくりした振幅の揺れ（これもループ長で整数周期）
        v *= 0.75 + 0.25 * math.sin(2 * math.pi * (2 / seconds) * t)
        v += noise_level * table[(i * 7919) % len(table)]
        samples.append(v * 0.5)
    write_wav(path, samples)


def chirp(path: Path, seconds: float, f0: float, f1: float, decay: float, noise: float, seed: int) -> None:
    total = int(SAMPLE_RATE * seconds)
    rng = Rng(seed)
    table = [rng.uniform(-1.0, 1.0) for _ in range(2048)]
    samples = []
    phase = 0.0
    for i in range(total):
        t = i / total
        freq = f0 + (f1 - f0) * t
        phase += 2 * math.pi * freq / SAMPLE_RATE
        env = math.exp(-decay * t) * min(1.0, i / 64)
        v = math.sin(phase) * env
        v += noise * table[(i * 7919) % len(table)] * env
        samples.append(v * 0.7)
    write_wav(path, samples)


def build_sounds(out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    # ステージ固有の環境音（8 秒ループ）
    ambience(out / "amb_hull.wav", 8.0, [(440, 0.5), (661, 0.25), (880, 0.14)], 0.05, seed=5)
    ambience(out / "amb_reactor.wav", 8.0, [(360, 0.45), (720, 0.3), (1081, 0.18)], 0.09, seed=6)
    ambience(out / "amb_vent.wav", 8.0, [(520, 0.4), (779, 0.3), (1560, 0.12)], 0.14, seed=7)
    # 全ステージ共有の SE
    chirp(out / "se_pickup.wav", 0.28, 620, 1560, 5.0, 0.02, seed=8)
    chirp(out / "se_hit.wav", 0.34, 220, 70, 4.0, 0.35, seed=9)


# --- MP4 -------------------------------------------------------------------


def build_video(out: Path) -> None:
    """背景ループ動画（stage1 のみ）。ffmpeg が無ければスキップして警告する。"""
    out.mkdir(parents=True, exist_ok=True)
    target = out / "backdrop_hull.mp4"
    if shutil.which("ffmpeg") is None:
        print("warning: ffmpeg not found — skipping backdrop_hull.mp4", file=sys.stderr)
        return
    graph = (
        "gradients=s=480x270:c0=0x04121c:c1=0x1d6b7d:c2=0x3ba8b8:c3=0x071d28"
        ":nb_colors=4:speed=0.02:x0=20:y0=30:x1=460:y1=240:d=8:r=20,"
        "geq=r='r(X,Y)*(0.55+0.45*sin((X+Y)/26+T*1.6))'"
        ":g='g(X,Y)*(0.55+0.45*sin((X+Y)/26+T*1.6))'"
        ":b='b(X,Y)*(0.6+0.4*sin((X+Y)/26+T*1.6))',"
        "vignette=PI/5,format=yuv420p"
    )
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", graph,
        "-t", "8", "-c:v", "h264_videotoolbox", "-b:v", "500k",
        str(target),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"warning: ffmpeg failed:\n{result.stderr}", file=sys.stderr)


def main() -> None:
    build_models(RES / "Models")
    build_images(RES / "Images")
    build_sounds(RES / "Sounds")
    build_video(RES / "Videos")
    for p in sorted(RES.rglob("*")):
        if p.is_file():
            print(f"{p.relative_to(RES)}  {p.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
